version: "3.8"
services:
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
  task-api:
    build:
      context: ./task-api
    ports:
      - "8080:8080"
    environment:
      - APP_DB_HOST=postgres
      - APP_DB_PORT=5432
      - APP_DB_PASS=postgres
      - APP_DB_NAME=postgres
      - APP_DB_MAX_CONN=3
      - APP_PORT=8080
      - GIN_MODE=release
    depends_on:
      - postgres
  task-ui:
    build:
      context: ./task-ui
    ports:
      - "80:80"
    depends_on:
      - task-api