name: Test conditional workflows
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Choose an action to run'
        required: true
        type: choice
        options:
          - test
          - deploy
          - cleanup
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests
        run: echo "Running tests" ${{ github.event.inputs.action }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to aws
        run: echo Deploying to aws
      - name: Pushing image to ECR
        run: echo Deploying to aws


